### ISSUE TITLE
example please

### ISSUE THREAD

**Issue by timeshift92** [sveltejs/svelte-hmr#1]

**Comment by rixo** [comment]
Hey! Thank you very much for issue number 1 :)

This repository contains the core implementation of Svelte HMR that is shared by all supported bundlers, but it does nothing useful on its own. It needs integration into a bundler specific plugin for a working solution.

Such integrations already exist for Webpack and Rollup. FYI I'm personally more interested in Rollup / Nollup support, and I'm currently focusing most of my effort on this, including documentation etc. So, regarding HMR, I recommend going with Rollup, if you have a choice.

For Webpack, you've got:

- My [fork of svelte-loader](https://github.com/rixo/svelte-loader) with HMR support. Unpublished (as its own npm pacakge) and undocumented for now.

- **The [original demo](https://github.com/rixo/demo-svelte3-hmr) that you can use as a starting point example, or even a template for a new project.**

- A [Sapper + HMR template](https://github.com/rixo/sapper-template-hot/tree/webpack) (notice: on the `webpack` branch).

- For completeness, this loader is also used in the [svelte-native-template](https://github.com/halfnelson/svelte-native-template).

For Rollup:

- [rollup-plugin-svelte-hot](https://github.com/rixo/rollup-plugin-svelte-hot) can be used instead of official Svelte plugin, to add HMR support. There _is_ already some docs in there! Go check it!

- **[svelte-template-hot](https://github.com/rixo/svelte-template-hot), that demonstrates usage with both Nollup and Rollup hot plugin. This is probably the example / starting point you need.**

- [rollup-plugin-hot](https://github.com/rixo/rollup-plugin-hot) is a plugin to add HMR support to Rollup. You'll need to use either this plugin or Nollup for HMR with Rollup. `svelte-template-hot` includes both. This plugin is still very much a work in progress but, regarding Svelte HMR and according to e2e tests, it's on par with other solutions.

I'm currently very interested in validating real word use cases from other people, so I'll be glad to help you with your specific setup. Let me know if you have further questions.

**Comment by rixo** [comment]
I've moved this information in the README to help people that may find this project first when searching for "svelte hmr".

Closing the issue since the templates / demo can serve as usage examples. Feel free to open an issue in one of the bundler plugin or template if it doesn't work for you.

**Comment by aral** [comment]
In case anyone’s looking to see how to use this module programmatically, a list of locations in the svelte-loader example that should help:

- Code transformation: https://github.com/rixo/svelte-loader/blob/ed4e5edd0dcec6c506574f7191e7daef1fe5e585/index.js#L130
- make-hot.js: https://github.com/rixo/svelte-loader/blob/master/lib/make-hot.js
