### ISSUE TITLE
Unable to resolve specifier 'svelte-hmr/runtime/proxy-adapter-dom.js'

### ISSUE THREAD

**Issue by flayks** [sveltejs/svelte-hmr#11]
I got this error lately, not really knowing why and where this come from. Tried with a fresh clone from the `svelte-template-hot` git repo, I get the same error.

![image](https://user-images.githubusercontent.com/273716/81578701-729ffe00-93ab-11ea-8ce3-dbc25d723a4e.png)

Any lead? 🙈

**Comment by rixo** [comment]
Hmm... This means imported module not found in SystemJS parlance (SystemJS is used as a module loader by rollup-plugin-hot). In this case it's an internal HMR file that should be present.

There's been a lingering issue with a recent version `@rollup/plugin-commonjs` that produces weird errors, and I've lagged to pin the version when Svelte official template did it... Hopefully it's just that: can you try to install `@rollup/plugin-commonjs@11.0.2` and see if it's better?

Otherwise I may have broken something on my side without realizing it, but I've just tried with a fresh clone of `svelte-template-hot` and both Rollup and Nollup went without issue (note I have just pinned said commonjs in the last days). Can you try again an see if you still have the issue with the currrent version?

**Comment by flayks** [comment]
I did try to install it again from scratch and I think I found the issue: `pnpm`. Idk why but it fucks up some installs sometimes, because installing modules with `npm install` runs smoothly.

I get this error only installing modules with pnpm:

> Error: Unable to resolve specifier 'svelte-hmr/runtime/proxy-adapter-dom.js' from http://localhost:5000/build/bundle.js@hot/src/App.svelte.js

🤷

**Comment by rixo** [comment]
Hmm ok, I see what it is now. I changed some import paths that were absolute to something relative for better support of native ES... But I guess it doesn't work with pnpm's file layout :-/

I'm reverting for now.

Can you confirm this is fixed for you with `rollup-plugin-svelte-hot@0.6.4`?

**Comment by intrnl** [comment]
`pnpm` fucking up sometimes could be attributed with it not producing a flat node modules directory like `yarn` and `npm` does :slightly_smiling_face: 
[see this part of faq for details](https://pnpm.js.org/en/faq#pnpm-does-not-work-with-your-project-here)

**Comment by rixo** [comment]
Presumed fixed in latest versions. Feel free to reopen if needed.
