### ISSUE TITLE
expose adapter path to config

### ISSUE THREAD

**Issue by intrnl** [sveltejs/svelte-hmr#13]
alongside the path to hot api, adapter path should be exposed as well.

this is to get vite and pnpm interop to work correctly without having `svelte-hmr` as peer dependency

making `svelte-hmr` a peer dependency in [`vite-plugin-svelte`](https://github.com/intrnl/vite-plugin-svelte) doesn't seem right, and the only possible solution is to create two runtime files on the plugin that will in turn import the ones from `svelte-hmr`

alternative solution would be to copy `createMakeHot` function over, but i think that it would be best to discuss about this first :slightly_smiling_face:

**Comment by rixo** [comment]
I must confess I'm a bit out of touch with the pnpm issue... Do you have a test case / repro that illustrates it?

You mean passing adapter path as argument to `createMakeHot`, right? That seems to make sense, but how would it solve the problem with pnpm?

**Comment by intrnl** [comment]
it should hopefully solve the problem with pnpm as now vite just has to resolve `vite-plugin-svelte/runtime/hot-api`, though i might have to do a test case for it to see if it actually solves the issue

**Comment by intrnl** [comment]
it seems that vite doesn't expose `.pnpm` folder as i thought it would, so while having custom hot api path and adapter path does work, it needs to be added into `optimizeDeps` so that it would be bundled

**Comment by intrnl** [comment]
or perhaps that could be from `npm link` causing vite to be confused about how to resolve, i might need to revise my test case here before showing.

**Comment by intrnl** [comment]
okay i've made a [test repo](https://github.com/intrnl/vite-pnpm-svelte-hmr) that should highlight what i got working.

vite does resolve `.pnpm` correctly, with the caveat that it can't resolve any deep imports located in the same directory, so it would fail on importing these, which is imported by the adapter and the hot api.
- `svelte-hmr/runtime/index.js`
- `svelte-hmr/runtime/overlay.js`

this can be fixed by adding them to `optimizeDeps`, which is probably the best solution at this point.

**Comment by rixo** [comment]
Thanks for the repo. I had to forage in the node_modules installed by pnpm to see the code because I didn't find anything on GitHub... I suppose you have everything in local?

I think I get the problem now. Your solution seems to make sense.

So, if I get this correctly, my take is that the best solution would be to keep by default absolute paths for svelte-hmr's runtime files (contrary to what I've just done in `0.9.0` uh uh). This way, bundlers that can resolve FS paths (Rollup, Webpack) can support both npm and pnpm without any change.

For bundlers that cannot resolve FS paths directly (Vite...), some additional workaround like the proxy files you've done seems unavoidable to support pnpm. So, for those, we'd have the option to provide custom paths for the hot api and the adapter.

Does this seem correct to you? I'm OK with doing that.

That being said, what's bothering me a little with your current solution is that if, for example, someone wants to wrap your `vite-plugin-svelte` in another package, they'll hit the same wall and have to redo the whole proxy files thing again... Can't we somehow instruct Vite that it should resolve a given import at a specific path (or URL?) instead of having proxy files?

BTW there's been a lot of discussion about Vite + Svelte in the Routify's discord recently. We've even just created a (no) bundler specific channel. @dominikg is also working on a Vite plugin for Svelte... You might be interested in joining us in there! Here's the Discord invit link: https://discord.gg/VPN625

**Comment by intrnl** [comment]
I'm not sure, perhaps it is better to keep `svelte-hmr` as a peer dependency for now?
Also, thanks for the invite!

**Comment by rixo** [comment]
@intrnl I have exposed the adapter path as `adapter` argument of `createMakeHot`: https://github.com/rixo/svelte-hmr/blob/458364e8ec4439e16b788efd8f9173aaf1ada25b/lib/make-hot.js#L161

This is published as `svelte-hmr@0.10.0-0` / `svelte-hmr@next`.

Can you confirm you can solve Vite + pnpm in vite-plugin-svelte with this?

**Comment by intrnl** [comment]
Can confirm it's solved in my end, available as `vite-plugin-svelte@1.4.0-next` for more testing.

**Comment by rixo** [comment]
FYI released as `svelte-hmr@0.10.0` (now `0.10.1` because of a dep update ^^) with no notable change.
