### ISSUE TITLE
Vite2 + Svelte with HMR support?

### ISSUE THREAD

**Issue by jsprog** [sveltejs/svelte-hmr#24]
Please understand that I already spent too much time before deciding about posting this issue here, and I think that this repository is the best fit for it at the moment:
- This all started after reading the deprecation notice at [https://github.com/intrnl/vite-plugin-svelte](https://github.com/intrnl/vite-plugin-svelte) about using [https://github.com/sveltejs/rollup-plugin-svelte](https://github.com/sveltejs/rollup-plugin-svelte) or [https://github.com/rixo/rollup-plugin-svelte-hot](https://github.com/rixo/rollup-plugin-svelte-hot) due to the official support for rollup plugins in Vite2. But the details are lacking. I tried to write something there but unfortunately, the repository is archived and read only.
- I already managed to use [https://github.com/sveltejs/rollup-plugin-svelte](https://github.com/sveltejs/rollup-plugin-svelte) with [svelte-preprocess](svelte-preprocess) and [https://github.com/sass/dart-sass](https://github.com/sass/dart-sass) by adding some minimal configuration and everything is working smoothly with development and production modes (see below).
- [https://github.com/vitejs/vite](https://github.com/vitejs/vite) isn't the right place for this issue for these reasons:
  - Vite2 is expecting the support for components libraries by using plugins (even for vue.js) [https://vitejs.dev/plugins/](https://vitejs.dev/plugins/)
  - This repository ([https://github.com/rixo/svelte-hmr](https://github.com/rixo/svelte-hmr)) is about bringing HMR support to svelte and Vite is already mentioned at **Svelte HMR tools** section. I'm not requesting that you support Vite2 but we may use this as a starting point for the crowd to join the discussion if any.

** This is the configuration I'm using for Vite2 + Svelte without HMR Support:**
```js
// vite.config.js

import svelte from 'rollup-plugin-svelte'
const preprocess = require('./svelte.config.js').preprocess // this is optional
const production = (process.env.NODE_ENV === 'production')

export default {
    plugins: [
        svelte({
            preprocess, // this is optional
            dev: !production,
            emitCss: false // this is needed during development to avoid error messages claiming about missing css files
                           // e.g: claiming about missing App.css!
        })
    ],
  optimizeDeps: {
    include: ['svelte/internal', 'svelte/store'] // likely you'll need to add more entries as you use some other modules in your app
                                                 // e.g: 'svelte/transition'
  }
}
```

Unfortunately, I'm failing to achieve the same thing based on some configuration content from [https://github.com/rixo/svelte-template-hot](https://github.com/rixo/svelte-template-hot) and this is expected as Vite2 is likely not using rollup-plugin-hot.

**Comment by rixo** [comment]
I think you're in right repo for this discussion. I guess the Rollup plugin would be ok too, because they've got crossed concerns... But whatever, currently all these issues get to me in the end.

You can still ping @intrnl here, if we need extra details, but I'm not sure that will be the case.

rollup-plugin-svelte-hot (via svelte-hmr) does a code transform on compiled Svelte components code to add HMR support. This has already been proven to work with Vite, in Svite and vite-plugin-svelte. So I don't see a reason why it wouldn't be working anymore...

Replacing rollup-plugin-svelte with rollup-plugin-svelte-hot in your above config should just work I guess.

Now, what's annoying is that the API of the official Rollup plugin recently changed, through 2 major versions, and rollup-plugin-svelte-hot is currently behind. This means you won't be able to swap the two anytime you want because the config (of the Svelte plugin) won't be compatible.

I'm not really planning to fix this, because the plan would rather be to integrate svelte-hmr into the official plugin and deprecate rollup-plugin-svelte-hot: https://github.com/sveltejs/rollup-plugin-svelte/pull/162

There are some hesitations though, as you can see in the PR's comments. The situation you've just brought about is strengthening my opinion that it should be done though, because Vite has core HMR and, if it now becomes a direct consumer of the Rollup plugin, it does make full sense to support the feature (the situation being less clear cut with just Rollup that doesn't have native HMR).

I'm curious to know if just swapping rollup-plugin-svelte-hot in your above config works for you. From what I see, the basic config you have for now shouldn't be impacted by the incompatibilities that have arisen recently (just don't forget to turn on the `hot` option).

**Comment by jsprog** [comment]
> I'm curious to know if just swapping rollup-plugin-svelte-hot in your above config works for you. From what I see, the basic config you have for now shouldn't be impacted by the incompatibilities that have arisen recently (just don't forget to turn on the hot option).

I appreciate your quick reply to the issue I created and sorry for not replying to your request very soon.

**Create vite2 (vuejs) project:**
```shell
npm init @vitejs/app
Project name: · vite2-svelte-hmr
Select a template: · vue

cd vite2-svelte-hmr
npm install
```

**Bring support for svelte without hmr:**
```shell
npm install -D svelte rollup-plugin-svelte
```
```js
// vite.config.js
import svelte from 'rollup-plugin-svelte'

const production = (process.env.NODE_ENV === 'production')

export default {
  plugins: [
    svelte({
      emitCss: false,
      dev: !production,
    })    
  ]
}
```
```js
// main.js

// we don't need vuejs
    // note that vite2 isn't using import.meta.hot.accept
    // nor import.meta.hot.dispose for vuejs
// import { createApp } from 'vue'
// import App from './App.vue'
// createApp(App).mount('#app')

import App from './App.svelte'
const app = new App({
    target: document.body,
});
export default app
```

```svelte
<!-- App.svelte -->
<script>
    import { onMount, onDestroy } from 'svelte'
    import TestComponent from './TestComponent.svelte'

    onMount(() => { console.log('Mount  : App.svelte'); console.log('') })
    onDestroy(() => { console.log('Destroy: App.svelte')})
</script>

<div>
    App.svelte
    <TestComponent />
</div>

<style>
    div { background-color: lime; }
</style>
```

```svelte
<!-- TestComponent.svelte -->
<script>
    import { onMount, onDestroy } from 'svelte'
    onMount(() => { console.log('mount  : TestComponent.svelte') })
    onDestroy(() => { console.log('destroy: TestComponent.svelte')})
</script>

<div class="test-component">
    TestComponent.svelte
</div>

<style>
    div { background-color: aqua; }
</style>
```

At this step, we're having a working project and saving TestComponent is triggering reload for the chrome browser (loading circle).

Lets swap `rollup-plugin-svelte` with `rollup-plugin-svelte-hot`:
```shell
npm install -D rollup-plugin-svelte-hot
```
```js
// vite.config.js
// import svelte from 'rollup-plugin-svelte'
import svelte from 'rollup-plugin-svelte-hot'
// ...
```

After testing again with dev mode, no problems at all and saving TestComponent.svelte is triggering reload for chrome browser (nothing changed).

**Trying to bring back HMR:**
All the attempts to bring back HMR failed after copying some configuration from [https://github.com/rixo/svelte-template-hot](https://github.com/rixo/svelte-template-hot).
Trying to introduce the following content is succeeding in preventing browser reload from firing (note: for this to work, don't use rollup-plugin-hot in vite.config.js), but can't prevent vite2 from reloading the full app (Likely vite2 is expecting something from the plugin for HMR support).
```js
// main.js
if (import.meta.hot) {
	import.meta.hot.accept();
	import.meta.hot.dispose(() => {
	  app.$destroy();
	});
}
```

**Comment by rixo** [comment]
Oh, thanks a lot! This allowed me to go straight to studying the issue :)

So, yeah the point of `svelte-hmr` is adding those `import.meta.hot.*` handlers automatically to Svelte components. And actually, it probably does in your last version, with `rollup-plugin-svelte-hot`.

You were almost there, but there's also an internal option that is needed for Vite, because it has special needs. In particular, it needs to see `import.meta.hot.accept()` in the component's module itself, which `svelte-hmr` isn't doing normally.

So, with the following `vite.config.js`, Svelte HMR seems to be working for me:

```js
import svelte from 'rollup-plugin-svelte-hot'

/**
 * @type {import('vite').UserConfig}
 */
export default {
  plugins: [
    svelte({
      dev: true,
      hot: {
        compatVite: true,
      },
    }),
  ],
}
```

I think I can remove the need for this compat option, at least for Vite 2.

Also, I don't have the time to test how HMR is doing with Vite 2 in depth because I don't have a Vite project I'm working on myself... So, again, I'm pretty curious to know how it goes for you, after using it for some time...

**Comment by rixo** [comment]
OK, I've removed the need for this option with Vite 2 in `svelte-hmr@0.12.4` (see, you did pick the right repo!).

So now, the last config you've tried should just work. Here's mine:

`vite.config.js`

```js
import svelte from 'rollup-plugin-svelte-hot'

export default {
  plugins: [
    svelte({
      dev: true,
      hot: true,
    }),
  ],
}
```

Note: be sure to remove your `package-lock.json` and reinstall (I think... not really sure how you do this with `npm` actually), in order to get the last version of `svelte-hmr`, since it's a transitive dependency. `npm ls` to be sure you've got `svelte-hmr@0.12.4`.

**Comment by jsprog** [comment]
It really worked with the last update. I could also confirm that I don't need to add `emitCss: false` and the app isn't claiming about missing CSS files anymore.

Other things I don't understand very well:
- `npm install -D svelte-hmr` isn't bringing `rollup-plugin-svelte-hot` and I had to install it manually.
- Adding svelte as non development dependency is triggering some errors about  deep import and the only way I could discover to suppress them are (even rollup-plugin-svelte is affected):
  - Adding the deep imports to `optimizeDeps` as mentioned above when creating this issue.
  - Or installing svelte as development dependency instead. This approach won't hurt and it may be useful in occasions when there's a need for `npm install --production`

Anyway, I already started a project a week ago, and time to get back to it, and by doing this, I should be able to report with any possible abnormalities effectively (hoping I won't face them).

**Comment by benmccann** [comment]
The Rollup support in Vite is nice, but it looks like you need a package like `vite-plugin-svelte` in order to support SSR. @intrnl is this something you might consider bringing back for Vite 2?

This is what I get when trying to create a server in SSR mode with Vite 2:
```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .svelte?import file format.
    at formatError (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53347:46)
    at TransformContext.error (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53343:19)
    at TransformContext.transform (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:46225:22)
    at async Object.transform (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53558:30)
    at async transformRequest (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:60171:29)
    at async ssrLoadModule (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:71337:10)
    at async Promise.all (index 0)
    at async ssrLoadModule (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:71343:5)
    at async /server.js:61:11
```

**Comment by benmccann** [comment]
The Rollup support in Vite is nice, but it looks like you need a package like `vite-plugin-svelte` in order to support SSR. @intrnl is this something you might consider bringing back for Vite 2?

This is what I get when trying to create a server in SSR mode with Vite 2:
```
Error: Failed to parse source for import analysis because the content contains invalid JS syntax. You may need to install appropriate plugins to handle the .svelte?import file format.
    at formatError (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53347:46)
    at TransformContext.error (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53343:19)
    at TransformContext.transform (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:46225:22)
    at async Object.transform (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:53558:30)
    at async transformRequest (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:60171:29)
    at async ssrLoadModule (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:71337:10)
    at async Promise.all (index 0)
    at async ssrLoadModule (/node_modules/vite/dist/node/chunks/dep-e56807a6.js:71343:5)
    at async /server.js:61:11
```

You can see my attempt at it here: https://github.com/benmccann/vite-svelte

**Comment by benmccann** [comment]
I tried to get SSR with Vite working as well, but only got it working in prod mode and not dev mode (https://github.com/vitejs/vite/issues/1655). Hopefully we can get it working in both modes with `rollup-plugin-svelte`. That would save us from having to create a separate `vite-plugin-svelte` as @intrnl did for Vite 1. If we have to create a `vite-plugin-svelte` for SSR it might make more sense to put the HMR support there than `rollup-plugin-svelte`. Though I expect we should be able to make `rollup-plugin-svelte` work with Vite dev-mode SSR directly

**Comment by dominikg** [comment]
when this PR  https://github.com/sveltejs/rollup-plugin-svelte/pull/162 lands it might just be a matter of implementing the vite specific hooks: https://vitejs.dev/guide/api-plugin.html#vite-specific-hooks

A vite-plugin-svelte that extends rollup-plugin-svelte like this https://vitejs.dev/guide/api-plugin.html#rollup-plugin-compatibility  could do the trick. I'd not do it in rollup-plugin-svelte directly for fear of breaking something in other rollup setups.

**Comment by rixo** [comment]
@jsprog 

> I could also confirm that I don't need to add `emitCss: false`

You don't need it with `rollup-plugin-svelte-hot`, because it automatically turns it off when `hot` is enabled.

Alternatively, you can try the proposed integration of `svelte-hmr` in the official Rollup plugin by installing the PR's branch from Github:

```bash
npm i -D rixo/rollup-plugin-svelte#svelte-hmr
```

You'll need `emitCss: false` for HMR then, because no auto disable mechanism is in place there (yet?).

> npm install -D svelte-hmr isn't bringing rollup-plugin-svelte-hot and I had to install it manually.

That's the reverse you need to do. `svelte-hmr` is a dependency of `rollup-plugin-svelte-hot`. So you need to install `rollup-plugin-svelte-hot` to (automatically) get a copy of `svelte-hmr`. However, if you already installed it before I published the last version of `svelte-hmr`, you may have to tell `npm` to update it somehow. I'm not really sure how, to be honest, maybe `npm update rollup-plugin-svelte-hot` would do it.

> Adding svelte as non development dependency is triggering some errors about deep import and the only way I could discover to suppress them are (even rollup-plugin-svelte is affected):

I think Vite bundles all your the (node_modules) deps that are used in your app to ES modules beforehand, so that they can be imported into the browser with native ES imports. It has to do that only once when your dependencies change, because they don't change otherwise, and this allows for fast subsequent "cold" starts.

Apparently, Vite is trying to automatically "optimize" any package that is present as a `dependencies` of your app, but not `devDependencies`. This makes sense, since dev dependencies are mostly Node stuff and all, that are not needed in the browser, and Vite would have a very hard time "optimizing". I think it's a bit abusing the concept of a normal vs dev dependency, because a dependency that gets bundled into your app should probably really be a dev dependency (meaning you don't need npm to pull it along your package, when you're installing it for consumption, as opposed to "for development"). Yet the point is a bit moot for "end of chain" apps (as opposed to libs), because you rarely ever install those as npm packages... So, all in all, Vite's system feels pretty practical and elegant.

What apparently happens is that, when optimizing, Vite is using the entrypoint declared in the package.json. In the case of Svelte, that's the browser runtime (the one exposing `onMount` and such). But during compilation, Svelte also adds imports from `svelte/internal` to your components. That's what Vite is complaining about with its "deep imports". `svelte/internal` is not visible from `package.json`, so Vite didn't optimize it and finds itself at a lost when the browser requires it... All of this seems pretty logical and expected to me.

Now, what's a bit more surprising (in a good way!) is that when Svelte is added as a dev dependency, it does seem to work with any fuss. How is that? I guess that's because Svelte already exports an ES version (meaning, no need to be "optimized" for the browser) of its internal, as an `index.mjs` file. Vite seems to have the smarts to pick that in priority over `index.js`, and so, in the end, Svelte doesn't need to be optimized at all. Said otherwise, it appears both Svelte and Vite do clever things and, as a result, they play along very well!

And so, AFAICT, the solution to this is really to add Svelte as a dev dep, like usual. Doing otherwise causes the deep imports issue, and is unneeded / suboptimal because Svelte is already bundled as browser-ready ES modules, and Vite would only rebundle it to ES module. And fail to see the deep imports in the process.

> Anyway, I already started a project a week ago, and time to get back to it, and by doing this, I should be able to report with any possible abnormalities effectively (hoping I won't face them).

Please, report success too, if that's the case... It would be good to know it works well too! :+1:

**Comment by rixo** [comment]
@benmccann 

> If we have to create a vite-plugin-svelte for SSR it might make more sense to put the HMR support there than rollup-plugin-svelte.

To be clear and totally transparent, HMR in the Rollup plugin would still be a need for me / Svench, independently of the Vite question. Svench is mostly used in Rollup projects for now, and I guess it will continue to be the case for some time. Beside, it relies heavily on HMR, and also needs to temper with user's config (to forcefully enable HMR, and inject its Svelte preprocessor)... and it makes things quite more complicated that there are 2 Rollup plugins out there, including one that don't support HMR.

With that, and considering that svelte-hmr is currently a kind of polyfill for Svelte HMR in the compiler, I still believe it would make sense for the Rollup plugin to feature HMR, even if a separate Vite plugin is still needed. The extra (little) complexity would be the same in the Rollup plugin or the Vite plugin, and it wouldn't have to be duplicated into the Vite plugin if the Rollup plugin already implements it. But if HMR is in the Rollup plugin, it would be useful both to Vite / the Vite plugin, and other HMR consumers, like Svench. And also, it will allow people to turn to "garage" solutions like Nollup, to speed up their dev, if they're stuck with a Rollup project they can't/won't migrate to a faster alternative. Past experience has shown that many were willing to try that, even with the current lightly documented community hot forks, and slower HMR experience delivered by `rollup-plugin-hot`.

**Comment by bhvngt** [comment]
Thanks for this very useful thread. 

I am trying to make vite 2 to work with svelte and hmr. So far with the help of [this comment](https://github.com/rixo/svelte-hmr/issues/24#issuecomment-764868771), I have been able to make it work. 

One issue that have troubling me is getting hmr to work with style block. I am using tailwindcss and for some unknown reason, hmr is not working when I make changes within the style block. It is not throwing any particular error. Its just not picking up the changes. I end up restarting vite to reflect style block changes.

Would anyone have idea around if I am missing something here?

Here are my config files

`vite.config.js`
```
import { defineConfig } from "vite";
import svelte from "rollup-plugin-svelte-hot";
import autoPreprocess from "svelte-preprocess";

export default defineConfig({
    root: "src",
    plugins: [
        svelte({
            preprocess: autoPreprocess(),
            dev: true,
            hot: true,
        }),
    ],
});
```

`svelte.config.js`
```
const autoPreprocess = require('svelte-preprocess');

module.exports = {
    preprocess: autoPreprocess({
        defaults: {
            script: 'typescript',
        },
    }),
};
```

`postcss.config.js`
```
module.exports = {
    plugins: {
        tailwindcss: {},
        autoprefixer: {},
    },
};
```

`tailwind.config.js`
```
module.exports = {
    purge: ["./index.html", "./src/**/*.svelte"],
    darkMode: false, // or 'media' or 'class'
    theme: {
        extend: {},
    },
    variants: {
        extend: {},
    },
    plugins: [
        require("@tailwindcss/typography"),
        require("@tailwindcss/forms"),
        require("@tailwindcss/aspect-ratio"),
    ],
};
```

**Comment by rixo** [comment]
@bhavinkamani-gt Hi!

I recommend against using `rollup-plugin-svelte-hot` in Vite at this point. The Vite support I've added in it was mainly experimentation for research purpose (and most of it lives in `rollup-plugin-svelte-hot@next`, not latest). Anyway, all development efforts of a Vite plugin (including mine) are currently focused on `@svitejs/vite-plugin-svelte`, so I recommend you use this plugin instead. @dominikg will tell you it is not prod ready yet, but it is already pretty stable, and it is the best we have currently.

It has a better handling of CSS in the context of Vite, so I think it will solve your style issue.

As a side note, current `rollup-plugin-svelte` or `rollup-plugin-svelte-hot` are **not** loading `svelte.config.js`, so it is just ignored in your current setup. `@svitejs/vite-plugin-svelte` will load it though, so you should probably remove the options you pass directly to the Svelte plugin when you migrate.

Also, @dominikg has been experimenting with Windicss with Vite 2, which is way faster than traditional Tailwind, so you might want to check this: https://github.com/svitejs/svite/tree/main/packages/playground/windicss

**Comment by jsprog** [comment]
The official svelte plugin for vite2 is available since more than 2 months ([vite-plugin-svelte](https://github.com/sveltejs/vite-plugin-svelte)) but nothing is mentioned about this in the readme page of this repository, nor in the page dedicated for [community plugins for vite2](https://github.com/vitejs/awesome-vite#plugins).

Is it time to close this issue?

**Comment by rixo** [comment]
Yes, indeed.

The official plugin is obviously the way to go.

I have updated the README with more up to date links and info.

Thanks for your feedback and the reminder :)
